# Generated by Django 5.1.5 on 2025-03-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_policycategory'),
        ('insurance', '0005_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='created_at',
            new_name='claim_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='user',
        ),
        migrations.AddField(
            model_name='claim',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=20),
        ),
    ]
