# Generated by Django 3.0.5 on 2025-03-18 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_policycategory'),
        ('insurance', '0006_rename_created_at_claim_claim_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claim_date',
        ),
        migrations.AddField(
            model_name='claim',
            name='reason',
            field=models.CharField(default='No reason provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
