# Generated by Django 3.0.5 on 2025-03-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20250318_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='reason',
        ),
    ]
