# Generated by Django 3.0.5 on 2025-03-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_claim_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='description',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='reason',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='claimant_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
