# Generated by Django 3.0.5 on 2025-03-26 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_auto_20250326_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claimant_name',
        ),
        migrations.AddField(
            model_name='claim',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_reason',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='claim',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='claims/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='policy_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
