# Generated by Django 3.0.5 on 2025-03-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_auto_20250330_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
