# Generated by Django 3.0.5 on 2025-01-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_policycategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyCategory',
        ),
    ]
