# Generated by Django 3.0.5 on 2025-03-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_claim_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Claim',
            new_name='Claims',
        ),
    ]
