# Generated by Django 3.0.5 on 2025-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20250327_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
