# Generated by Django 3.0.5 on 2025-03-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20250327_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='supporting_document',
            field=models.ImageField(upload_to='claims/'),
        ),
    ]
